'use strict';
const token=location.hash.slice(1);history.replaceState(null,'',location.pathname);
const $=id=>document.getElementById(id);let snapshot,previewed='',records=[];
const say=message=>{$('notice').textContent=message};
async function api(path,body){const response=await fetch(path,{method:body?'POST':'GET',headers:{'X-Console-Token':token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw Error(data.error||'İşlem başarısız.');return data;}
function list(id,items){$(id).replaceChildren(...items.map(text=>{const li=document.createElement('li');li.textContent=text;return li}));}
async function load(){snapshot=await api('/api/settings?target='+$('target').value);$('path').textContent=snapshot.target;$('setup').textContent=snapshot.installed?'Yönetilen kurulum bulundu.':'Bu projede yönetilen kurulum bulunamadı. Konsol yalnızca model ve adım ayarlarını kaydeder. Ajanları ve güvenlik rollerini kurmak için dağıtım deposunda: python3 scripts/install.py --target PROJE --action install --profile balanced';$('effective').textContent=JSON.stringify({model:snapshot.effective.model,roles:snapshot.effective.roles},null,2);$('model').value=snapshot.model||'';$('profile').replaceChildren(...[...snapshot.profiles,'custom'].map(value=>{const o=new Option(({balanced:"Dengeli",quality:"Yüksek kalite",economy:"Ekonomik","quota-saver":"Kota tasarrufu",custom:"Özel"})[value],value);return o}));$('profile').value='custom';$('roles').replaceChildren(...Object.entries(snapshot.roles).map(([role,values])=>{const label=document.createElement('label');label.textContent=role;const input=document.createElement('input');input.dataset.role=role;input.value=values.model||'';input.placeholder='Miras alınan model';label.append(input);return label}));list('limits',snapshot.limitations);$('save').disabled=true;previewed='';$('diff').textContent='Kaydetmeden önce farkı önizleyin.';}
function settings(){return{revision:snapshot.revision,profile:$('profile').value,model:$('model').value.trim(),roles:Object.fromEntries([...document.querySelectorAll('[data-role]')].map(input=>[input.dataset.role,{model:input.value.trim()}])),allow_mixed:$('mixed').checked,replace:$('replace').checked};}
function action(fn){return async()=>{try{await fn()}catch(error){say(error.message)}}}
$('target').onchange=action(load);
$('settings').addEventListener('input',()=>{$('save').disabled=true;previewed=''});
$('preview').onclick=action(async()=>{const payload=settings();const result=await api('/api/preview',{target:$('target').value,settings:payload});$('diff').textContent=result.diff;previewed=JSON.stringify(payload);$('save').disabled=!result.fields;say('Doğrulandı. Yalnızca gösterilen alanlar kaydedilecek.');});
$('save').onclick=action(async()=>{const payload=settings();if(JSON.stringify(payload)!==previewed)throw Error('Ayarlar değişti; tekrar önizleyin.');await api('/api/save',{target:$('target').value,settings:payload});await load();say('Ayarlar yedeklenerek kaydedildi. Yeni OpenCode oturumunda kontrol edin.');});
$('restore').onclick=action(async()=>{await api('/api/restore',{target:$('target').value,revision:snapshot.revision});await load();say('Son konsol kaydı geri alındı; diğer alanlar korundu.');});
const labels={input:'Girdi',cache_read:'Önbellek okuma',cache_write:'Önbellek yazma',output:'Çıktı',reasoning:'Akıl yürütme',sessions:'Oturum',messages:'Mesaj'};
$('refresh').onclick=action(async()=>{const query=new URLSearchParams();if($('days').value)query.set('days',$('days').value);if($('scope').value==='current')query.set('project','');const data=await api('/api/usage?'+query);$('source').textContent=data.source+' · '+data.status+ (data.error?' · '+data.error:'');$('metrics').replaceChildren(...Object.entries(labels).map(([key,label])=>{const item=document.createElement('div');item.className='metric';item.textContent=label;const value=document.createElement('strong');value.textContent=data.observed?.[key]===undefined?'—':(data.rounded?.includes(key)?'≈ ':'')+Number(data.observed[key]).toLocaleString('tr-TR');item.append(value);return item}));list('usageLimits',data.limitations||['CLI bulunamazsa kullanım mevcut değildir.']);});
function renderRecords(){const selected=$('taskModel').value;const rows=records.filter(record=>!selected||record.model===selected);$('records').replaceChildren(...rows.map(record=>{const row=document.createElement('tr');for(const value of [record.thread,(record.provider||'')+'/'+(record.model||'—')+' / '+(record.agent||'—'),record.observed.input??'—',record.observed.cache_read??'—',record.observed.output??'—']){const cell=document.createElement('td');cell.textContent=value;row.append(cell)}return row}));}
$('taskLoad').onclick=action(async()=>{const session=$('session').value.trim();if(!session)throw Error('Gerçek bir oturum kimliği girin.');const data=await api('/api/usage?session='+encodeURIComponent(session));records=data.records||[];$('taskSource').textContent=data.source+' · '+data.status+(data.error?' · '+data.error:'');$('taskModel').replaceChildren(new Option('Tüm modeller',''),...[...new Set(records.map(record=>record.model).filter(Boolean))].map(model=>new Option(model,model)));renderRecords();});$('taskModel').onchange=renderRecords;
for(const button of document.querySelectorAll('[data-tab]'))button.onclick=()=>{for(const id of ['settings','usage','tasks'])$(id).hidden=id!==button.dataset.tab;for(const b of document.querySelectorAll('[data-tab]'))b.setAttribute('aria-pressed',String(b===button));};
action(load)();
